// src/lib/regulatory/sourceVerification.ts
// Phase 1: Source-Truth Verification System

import { createClient } from '@supabase/supabase-js'
import type { Database } from '@/types/supabase'

// Use SERVICE ROLE key for admin operations (bypasses RLS)
const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY!

const supabase = createClient<Database>(supabaseUrl, supabaseServiceKey)

export interface VerifiedClaim {
  isVerified: boolean
  matchingFacts: {
    factId: string
    claim: string
    sourceName: string
    sourceUrl: string
  }[]
  confidenceScore: number
}

export interface RegulatoryFact {
  id: string
  stateCode: string
  claim: string
  category: string
  sourceName: string
  sourceUrl: string
  sourceDate: string
  verificationStatus: 'verified' | 'pending_review' | 'needs_update' | 'deprecated'
  numericValue: number | null
  numericUnit: string | null
  notes: string | null
}

/**
 * Verify a claim against the regulatory_facts database
 * Uses the database function verify_claim() for efficiency
 */
export async function verifyClaim(
  claimText: string,
  stateCode: string
): Promise<VerifiedClaim> {
  try {
    // Call the database function we created in SQL
    const { data, error } = await supabase.rpc('verify_claim', {
      input_claim: claimText,
      input_state_code: stateCode
    })

    if (error) {
      console.error('❌ verifyClaim RPC error:', error)
      return {
        isVerified: false,
        matchingFacts: [],
        confidenceScore: 0
      }
    }

    return {
      isVerified: data?.is_verified || false,
      matchingFacts: data?.matching_facts || [],
      confidenceScore: data?.confidence_score || 0
    }
  } catch (error) {
    console.error('❌ verifyClaim exception:', error)
    return {
      isVerified: false,
      matchingFacts: [],
      confidenceScore: 0
    }
  }
}

/**
 * Get all verified facts for a specific state
 */
export async function getVerifiedFactsForState(
  stateCode: string,
  category?: string
): Promise<RegulatoryFact[]> {
  let query = supabase
    .from('regulatory_facts')
    .select('*')
    .eq('state_code', stateCode)
    .eq('verification_status', 'verified')
    .is('expires_at', null)
    .or('expires_at.gt.now()')

  if (category) {
    query = query.eq('category', category)
  }

  const { data, error } = await query

  if (error) {
    console.error('❌ getVerifiedFactsForState error:', error)
    return []
  }

  return data || []
}

/**
 * Get a single fact by ID
 */
export async function getFactById(factId: string): Promise<RegulatoryFact | null> {
  const { data, error } = await supabase
    .from('regulatory_facts')
    .select('*')
    .eq('id', factId)
    .single()

  if (error) {
    console.error('❌ getFactById error:', error)
    return null
  }

  return data
}

/**
 * Record a claim generated by AI for later verification
 */
export async function recordClaim(
  reportId: string,
  claim: string,
  supportingFactIds: string[] = []
): Promise<{ success: boolean; claimId?: string; error?: string }> {
  try {
    const { data, error } = await supabase
      .from('report_claims')
      .insert({
        report_id: reportId,
        claim: claim,
        supporting_fact_ids: supportingFactIds,
        verification_status: 'needs_review',
        created_at: new Date().toISOString()
      })
      .select('id')
      .single()

    if (error) {
      console.error('❌ recordClaim error:', error)
      return { success: false, error: error.message }
    }

    return { success: true, claimId: data.id }
  } catch (error) {
    console.error('❌ recordClaim exception:', error)
    return { success: false, error: String(error) }
  }
}

/**
 * Update verification status for a claim
 */
export async function updateClaimVerification(
  claimId: string,
  status: 'verified' | 'unverified' | 'hallucination' | 'needs_review',
  score: number,
  notes?: string
): Promise<boolean> {
  try {
    const { error } = await supabase
      .from('report_claims')
      .update({
        verification_status: status,
        verification_score: score,
        verification_notes: notes,
        verified_at: new Date().toISOString()
      })
      .eq('id', claimId)

    if (error) {
      console.error('❌ updateClaimVerification error:', error)
      return false
    }

    return true
  } catch (error) {
    console.error('❌ updateClaimVerification exception:', error)
    return false
  }
}

/**
 * Get all claims for a report
 */
export async function getClaimsForReport(reportId: string) {
  const { data, error } = await supabase
    .from('report_claims')
    .select('*')
    .eq('report_id', reportId)
    .order('created_at', { ascending: false })

  if (error) {
    console.error('❌ getClaimsForReport error:', error)
    return []
  }

  return data
}

/**
 * Calculate hallucination rate for a report
 */
export async function getHallucinationRate(reportId: string): Promise<{
  totalClaims: number
  verifiedCount: number
  hallucinationCount: number
  rate: number
}> {
  const claims = await getClaimsForReport(reportId)
  
  const totalClaims = claims.length
  const verifiedCount = claims.filter(c => c.verification_status === 'verified').length
  const hallucinationCount = claims.filter(c => c.verification_status === 'hallucination').length
  
  return {
    totalClaims,
    verifiedCount,
    hallucinationCount,
    rate: totalClaims > 0 ? (hallucinationCount / totalClaims) * 100 : 0
  }
}

/**
 * Insert a new verified fact into the database
 */
export async function insertVerifiedFact(
  fact: Omit<RegulatoryFact, 'id'>
): Promise<{ success: boolean; factId?: string; error?: string }> {
  const { data, error } = await supabase
    .from('regulatory_facts')
    .insert({
      state_code: fact.stateCode,
      claim: fact.claim,
      category: fact.category as any,
      source_name: fact.sourceName,
      source_url: fact.sourceUrl,
      source_date: fact.sourceDate,
      verification_status: 'verified',
      numeric_value: fact.numericValue,
      numeric_unit: fact.numericUnit,
      notes: fact.notes
    })
    .select('id')
    .single()

  if (error) {
    console.error('❌ insertVerifiedFact error:', error)
    return { success: false, error: error.message }
  }

  return { success: true, factId: data.id }
}