// Major US cities for location intelligence
export const MAJOR_CITIES = [
  { city: 'New York', state: 'NY', population: 8419000, region: 'Northeast' },
  { city: 'Los Angeles', state: 'CA', population: 3929000, region: 'West' },
  { city: 'Chicago', state: 'IL', population: 2716000, region: 'Midwest' },
  { city: 'Houston', state: 'TX', population: 2303000, region: 'South' },
  { city: 'Phoenix', state: 'AZ', population: 1608000, region: 'West' },
  { city: 'Philadelphia', state: 'PA', population: 1584000, region: 'Northeast' },
  { city: 'San Antonio', state: 'TX', population: 1547000, region: 'South' },
  { city: 'San Diego', state: 'CA', population: 1387000, region: 'West' },
  { city: 'Dallas', state: 'TX', population: 1344000, region: 'South' },
  { city: 'Austin', state: 'TX', population: 974000, region: 'South' },
  { city: 'San Jose', state: 'CA', population: 971000, region: 'West' },
  { city: 'Fort Worth', state: 'TX', population: 958000, region: 'South' },
  { city: 'Jacksonville', state: 'FL', population: 954000, region: 'South' },
  { city: 'Charlotte', state: 'NC', population: 910000, region: 'South' },
  { city: 'Columbus', state: 'OH', population: 907000, region: 'Midwest' },
  { city: 'Indianapolis', state: 'IN', population: 876000, region: 'Midwest' },
  { city: 'San Francisco', state: 'CA', population: 815000, region: 'West' },
  { city: 'Seattle', state: 'WA', population: 794000, region: 'West' },
  { city: 'Denver', state: 'CO', population: 734000, region: 'West' },
  { city: 'Washington', state: 'DC', population: 712000, region: 'Northeast' },
  { city: 'Boston', state: 'MA', population: 692000, region: 'Northeast' },
  { city: 'Nashville', state: 'TN', population: 678000, region: 'South' },
  { city: 'Portland', state: 'OR', population: 652000, region: 'West' },
  { city: 'Las Vegas', state: 'NV', population: 656000, region: 'West' },
  { city: 'Miami', state: 'FL', population: 442000, region: 'South' },
  { city: 'Atlanta', state: 'GA', population: 498000, region: 'South' },
] as const

// Web3 hubs (cities with strong blockchain ecosystems)
export const WEB3_HUBS = [
  { city: 'San Francisco', state: 'CA', type: 'primary', score: 98 },
  { city: 'New York', state: 'NY', type: 'primary', score: 95 },
  { city: 'Austin', state: 'TX', type: 'primary', score: 92 },
  { city: 'Miami', state: 'FL', type: 'primary', score: 90 },
  { city: 'Los Angeles', state: 'CA', type: 'secondary', score: 85 },
  { city: 'Chicago', state: 'IL', type: 'secondary', score: 82 },
  { city: 'Seattle', state: 'WA', type: 'secondary', score: 80 },
  { city: 'Denver', state: 'CO', type: 'secondary', score: 78 },
  { city: 'Boston', state: 'MA', type: 'secondary', score: 76 },
  { city: 'San Diego', state: 'CA', type: 'secondary', score: 74 },
] as const

// Metropolitan Statistical Areas
export const MSAS = [
  { name: 'New York-Newark-Jersey City, NY-NJ-PA', states: ['NY', 'NJ', 'PA'], population: 19300000 },
  { name: 'Los Angeles-Long Beach-Anaheim, CA', states: ['CA'], population: 13200000 },
  { name: 'Chicago-Naperville-Elgin, IL-IN-WI', states: ['IL', 'IN', 'WI'], population: 9500000 },
  { name: 'Dallas-Fort Worth-Arlington, TX', states: ['TX'], population: 7500000 },
  { name: 'Houston-The Woodlands-Sugar Land, TX', states: ['TX'], population: 7000000 },
  { name: 'Washington-Arlington-Alexandria, DC-VA-MD-WV', states: ['DC', 'VA', 'MD', 'WV'], population: 6300000 },
  { name: 'Miami-Fort Lauderdale-West Palm Beach, FL', states: ['FL'], population: 6200000 },
  { name: 'Philadelphia-Camden-Wilmington, PA-NJ-DE-MD', states: ['PA', 'NJ', 'DE', 'MD'], population: 6100000 },
  { name: 'Atlanta-Sandy Springs-Roswell, GA', states: ['GA'], population: 5900000 },
  { name: 'Boston-Cambridge-Newton, MA-NH', states: ['MA', 'NH'], population: 4900000 },
  { name: 'Phoenix-Mesa-Scottsdale, AZ', states: ['AZ'], population: 4900000 },
  { name: 'San Francisco-Oakland-Hayward, CA', states: ['CA'], population: 4700000 },
  { name: 'Riverside-San Bernardino-Ontario, CA', states: ['CA'], population: 4600000 },
  { name: 'Detroit-Warren-Dearborn, MI', states: ['MI'], population: 4300000 },
  { name: 'Seattle-Tacoma-Bellevue, WA', states: ['WA'], population: 3900000 },
  { name: 'Minneapolis-St. Paul-Bloomington, MN-WI', states: ['MN', 'WI'], population: 3600000 },
  { name: 'San Diego-Carlsbad, CA', states: ['CA'], population: 3300000 },
  { name: 'Tampa-St. Petersburg-Clearwater, FL', states: ['FL'], population: 3200000 },
  { name: 'Denver-Aurora-Lakewood, CO', states: ['CO'], population: 2900000 },
  { name: 'Baltimore-Columbia-Towson, MD', states: ['MD'], population: 2800000 },
] as const